Repository sonic16x/interslavic, pull requests merged in 2021-05, with the labels that each got.

#141 fix translation modal
  src/components/TranslationsModal/index.tsx
Labels: bug

#129 slight refactor of verb conjugation
  src/legacy/conjugationVerb.ts
Labels: Tech debt

#146 Viewer
  package-lock.json
  package.json
  src/actions/index.ts
  src/components/About/index.tsx
  src/components/Button/Button.scss
  src/components/Button/Button.tsx
  src/components/Checkbox/iamges/checked-icon.svg
  src/components/Checkbox/iamges/part-checked-icon.svg
  src/components/Checkbox/index.scss
  src/components/Checkbox/index.tsx
  src/components/DetailModal/index.tsx
  src/components/Header/index.scss
  src/components/Header/index.tsx
  src/components/ModalDialog/index.tsx
  src/components/Results/index.tsx
  src/components/ResultsCard/index.tsx
  src/components/Router/index.tsx
  src/components/Settings/index.tsx
  src/components/TranslationsModal/index.tsx
  src/components/Viewer/ViewerContextMenu.scss
  src/components/Viewer/ViewerContextMenu.tsx
  src/components/Viewer/ViewerHeaderComponent.scss
  src/components/Viewer/ViewerHeaderComponent.tsx
  src/components/Viewer/ViewerPOSFilterComponent.scss
  src/components/Viewer/ViewerPOSFilterComponent.tsx
  src/components/Viewer/images/context-menu-close-icon.svg
  src/components/Viewer/images/expand-sub-list-icon.svg
  src/components/Viewer/images/filter-icon.svg
  src/components/Viewer/images/filter-remove-icon.svg
  src/components/Viewer/images/sort-arrow-icon.svg
  src/components/Viewer/index.scss
  src/components/Viewer/index.tsx
  src/consts.ts
  src/hooks/useEnabledPages.ts
  src/hooks/useTablesMapFunction.ts
  src/index.scss
  src/index.tsx
  src/middlewares/localStorageMiddleware.ts
  src/reducers/index.ts
  src/routing/index.ts
  src/services/dictionary.ts
  src/services/fetchDictionary.ts
  src/services/generateDictionary.ts
  src/services/loadTablesData.ts
  src/translations/data.json
  src/utils/getAllDataFromResults.ts
  src/utils/getColumnName.ts
  src/utils/getTableDataUrl.ts
  src/utils/getTablePublicUrl.ts
  src/utils/isMainTable.ts
  src/utils/wordDetails.ts
  src/utils/wordHasForms.ts
  webpack.config.dev.js
  webpack.config.prod.js
Labels: Research
